
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param code
     * @return
     *     returns ws.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "ws.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "ws.GetCompteResponse")
    @Action(input = "http://ws/BanqueService/getCompteRequest", output = "http://ws/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://ws/", className = "ws.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://ws/", className = "ws.GetComptesResponse")
    @Action(input = "http://ws/BanqueService/getComptesRequest", output = "http://ws/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param soldes
     */
    @WebMethod
    @RequestWrapper(localName = "addComptes", targetNamespace = "http://ws/", className = "ws.AddComptes")
    @ResponseWrapper(localName = "addComptesResponse", targetNamespace = "http://ws/", className = "ws.AddComptesResponse")
    @Action(input = "http://ws/BanqueService/addComptesRequest", output = "http://ws/BanqueService/addComptesResponse")
    public void addComptes(
        @WebParam(name = "soldes", targetNamespace = "")
        String soldes);

    /**
     * 
     * @param compte
     */
    @WebMethod
    @RequestWrapper(localName = "addComptes2", targetNamespace = "http://ws/", className = "ws.AddComptes2")
    @ResponseWrapper(localName = "addComptes2Response", targetNamespace = "http://ws/", className = "ws.AddComptes2Response")
    @Action(input = "http://ws/BanqueService/addComptes2Request", output = "http://ws/BanqueService/addComptes2Response")
    public void addComptes2(
        @WebParam(name = "compte", targetNamespace = "http://ws/")
        List<Compte> compte);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDollar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDollar", targetNamespace = "http://ws/", className = "ws.ConversionEuroToDollar")
    @ResponseWrapper(localName = "ConversionEuroToDollarResponse", targetNamespace = "http://ws/", className = "ws.ConversionEuroToDollarResponse")
    @Action(input = "http://ws/BanqueService/ConversionEuroToDollarRequest", output = "http://ws/BanqueService/ConversionEuroToDollarResponse")
    public double conversionEuroToDollar(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param solde
     */
    @WebMethod
    @RequestWrapper(localName = "addCompte", targetNamespace = "http://ws/", className = "ws.AddCompte")
    @ResponseWrapper(localName = "addCompteResponse", targetNamespace = "http://ws/", className = "ws.AddCompteResponse")
    @Action(input = "http://ws/BanqueService/addCompteRequest", output = "http://ws/BanqueService/addCompteResponse")
    public void addCompte(
        @WebParam(name = "solde", targetNamespace = "")
        float solde);

    /**
     * 
     * @param compte
     */
    @WebMethod
    @RequestWrapper(localName = "addCompte2", targetNamespace = "http://ws/", className = "ws.AddCompte2")
    @ResponseWrapper(localName = "addCompte2Response", targetNamespace = "http://ws/", className = "ws.AddCompte2Response")
    @Action(input = "http://ws/BanqueService/addCompte2Request", output = "http://ws/BanqueService/addCompte2Response")
    public void addCompte2(
        @WebParam(name = "compte", targetNamespace = "http://ws/")
        Compte compte);

}
